# Generated by Django 4.0.3 on 2022-03-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_rename_fechcaducidad_entrada_fechacaducidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
