# Generated by Django 4.0.3 on 2022-03-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_evento_precioentrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('V', 'Vender'), ('C', 'Comprar')], default=int, max_length=1),
            preserve_default=False,
        ),
    ]
