# Generated by Django 4.0.3 on 2022-04-03 15:52

import datetime
import django.core.validators
from django.db import migrations, models
import localflavor.es.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_alter_evento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cif',
            field=localflavor.es.models.ESIdentityCardNumberField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 4, 4, 15, 52, 58, 924865))], verbose_name='Fecha'),
        ),
    ]
