# Generated by Django 4.0.3 on 2022-04-03 15:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_alter_empresa_cif_alter_evento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 4, 4, 15, 53, 2, 517558))], verbose_name='Fecha'),
        ),
    ]
