# Generated by Django 3.2.9 on 2022-03-26 22:42

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_merge_20220326_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 27, 22, 42, 42, 419361, tzinfo=utc))], verbose_name='YYYY-MM-DD HH:mm'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='precioEntrada',
            field=models.PositiveIntegerField(verbose_name='Precio Entrada'),
        ),
    ]
