# Generated by Django 3.2.9 on 2022-03-26 22:46

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_auto_20220326_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 27, 22, 46, 1, 624044, tzinfo=utc))], verbose_name='YYYY-MM-DD HH:mm'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='totalEntradas',
            field=models.PositiveIntegerField(verbose_name='Total Entradas'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(max_length=100, verbose_name='Ubicación'),
        ),
    ]
