# Generated by Django 3.2.9 on 2022-03-26 22:53

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_alter_evento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 27, 22, 53, 46, 326023, tzinfo=utc))], verbose_name='Fecha'),
        ),
    ]
