# Generated by Django 3.2.9 on 2022-03-28 10:44

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_alter_evento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 29, 10, 44, 25, 686854, tzinfo=utc))], verbose_name='Fecha'),
        ),
    ]
