# Generated by Django 4.0.3 on 2022-03-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='fechCaducidad',
            new_name='fechaCaducidad',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='fechCompra',
            new_name='fechaCompra',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='fech',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
