# Generated by Django 4.0.3 on 2022-04-02 10:40

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 4, 3, 10, 40, 5, 737197, tzinfo=utc))], verbose_name='YYYY-MM-DD HH:mm'),
        ),
    ]
