# Generated by Django 4.0.3 on 2022-03-23 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAudit', models.DateTimeField()),
                ('fechaLimite', models.DateTimeField()),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrada', to='proyecto.entrada')),
                ('nuevo_cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='nuevo_cliente', to='proyecto.evento')),
            ],
        ),
    ]
