# Generated by Django 4.0.3 on 2022-03-22 18:54

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_alter_evento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 23, 18, 54, 33, 230776, tzinfo=utc))], verbose_name='YYYY-MM-DD HH:mm'),
        ),
    ]
