# Generated by Django 4.0.3 on 2022-03-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='precioEntrada',
        ),
    ]
