# Generated by Django 4.0.3 on 2022-03-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_remove_evento_precioentrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='precioEntrada',
            field=models.PositiveIntegerField(default=40),
            preserve_default=False,
        ),
    ]
