# Generated by Django 4.0.3 on 2022-03-22 19:00

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_alter_evento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 23, 19, 0, 28, 222921, tzinfo=utc))], verbose_name='YYYY-MM-DD HH:mm'),
        ),
    ]
