# Generated by Django 4.0.3 on 2022-03-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_transaccion_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='nuevo_cliente',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_trans', to='proyecto.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='evento',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='evento_trans', to='proyecto.evento'),
            preserve_default=False,
        ),
    ]
