# Generated by Django 4.0.3 on 2022-03-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_evento_fecha'),
        ('proyecto', '0006_remove_transaccion_entrada_and_more'),
    ]

    operations = [
    ]
