# Generated by Django 3.2.9 on 2022-03-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_evento_fecha'),
        ('proyecto', '0006_remove_transaccion_entrada_and_more'),
    ]

    operations = [
    ]
