# Generated by Django 4.0.3 on 2022-03-27 13:47

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_merge_20220327_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 28, 13, 47, 2, 71096, tzinfo=utc))], verbose_name='YYYY-MM-DD HH:mm'),
        ),
    ]
