# Generated by Django 4.0.3 on 2022-03-27 09:04

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_merge_20220327_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 28, 9, 4, 12, 764090, tzinfo=utc))], verbose_name='YYYY-MM-DD HH:mm'),
        ),
    ]
