# Generated by Django 3.2.9 on 2022-03-26 15:36

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_merge_20220326_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 27, 15, 36, 7, 127094, tzinfo=utc))], verbose_name='YYYY-MM-DD HH:mm'),
        ),
    ]
