# Generated by Django 4.0.3 on 2022-03-27 14:07

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_alter_cliente_tlf_alter_empresa_tlf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 28, 14, 7, 10, 52552, tzinfo=utc))], verbose_name='YYYY-MM-DD HH:mm'),
        ),
    ]
