# Generated by Django 4.0.3 on 2022-03-29 17:08

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_rename_user_empleado_user1_alter_evento_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='user1',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 30, 17, 8, 9, 214243, tzinfo=utc))], verbose_name='YYYY-MM-DD HH:mm'),
        ),
    ]
