# Generated by Django 4.0.3 on 2022-03-30 19:41

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_rename_user1_empleado_user_alter_evento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 31, 19, 41, 46, 83751, tzinfo=utc))], verbose_name='YYYY-MM-DD HH:mm'),
        ),
    ]
