# Generated by Django 4.0.3 on 2022-03-30 20:06

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import localflavor.es.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_alter_evento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cif',
            field=localflavor.es.models.ESIdentityCardNumberField(default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 31, 20, 5, 53, 355164, tzinfo=utc))], verbose_name='YYYY-MM-DD HH:mm'),
        ),
    ]
