# Generated by Django 4.0.3 on 2022-03-30 20:06

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0017_empresa_cif_alter_evento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 3, 31, 20, 6, 15, 751810, tzinfo=utc))], verbose_name='YYYY-MM-DD HH:mm'),
        ),
    ]
